### ISSUE TITLE
Bahnschrift font license issue

### ISSUE THREAD

**Issue by oldherl** [rwev/tundra#2]
I noticed that your theme included a webfont file for Bahnschrift font family. Is that the same font as the Bahnschrift font in Windows? According to [MS Typography][1] page, it can't be redistributed without permission. If so, please consider replacing it with a free font for legal reasons.

[1]: https://docs.microsoft.com/en-us/typography/font-list/bahnschrift

**Comment by rwev** [comment]
Fair point, thanks for bringing this up. Must have missed or confused the licensing terms when I first added Bahnschrift. Anyway, I just removed the font and replaced its usages with FiraCode for now.
